program: WandBSkinSegmentation.py

method: random

project: "skin_segmentation"

metric:
  name: f1_score
  goal: maximize

parameters:
  num_epochs:
    value: 10
  batch_size: 
    value: 64
  train_size: 
    value: 1024
  test_size:
    value: 128
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.01
  momentum:
    distribution: uniform
    min: 0.9
    max: 0.999
  loss_function: 
    value: "IoU"
