program: SkinPixelSegmentation.py

# method: random
method: grid

project: "pixel_skin_segmentation"

metric:
  name: test_F1_loss
  goal: maximize

parameters:
  num_epochs:
    value: 25
  batch_size: 
    value: 256
  train_size: 
    # value: 10000
    value: 91539
  test_size:
    # value: 1000
    value: 10171
  lr:
    # value: 0.0001
    values:
      # - 0.0001
      - 0.001
    # values: 
    #   distribution: uniform
    #   min: 0.001
    #   max: 0.01
  momentum:
    # value: 0.9
    values:
      # - 0.9
      - 0.99
      # - 0.999
    # values: 
    #   distribution: uniform
    #   min: 0.9
    #   max: 0.99
  colour_space: 
    # value: "RGB"
    values:
    - "RGB"
    - "YCrCb"
    # value: "BCE"
    values: 
      - "BCE"
      # - "WBCE"
      # - "WBCE_0.9"
      # - "WBCE_0.7"
      # - "WBCE_0.3"
      # - "WBCE_0.1"
      # - "IoU"
      # - "Focal"
      - "L1"
  optimizer:
    value: "RMSprop"
    # values: 
    #   - "SGD"
    #   - "RMSprop"
    #   - "Adam"