program: WandBSkinSegmentation.py

command: 
 - ${env}
 - python3
 - ${program}
 - ${args}

# method: random
method: grid

project: "skin_segmentation"

metric:
  name: test_IoU
  goal: maximize

parameters:
  num_workers:
    values:
      - 1
      - 4
      - 8
  num_epochs:
    value: 2
  batch_size: 
    values: 
      - 16
      - 32
      - 64
  train_size: 
    value: 1024
  validation_size: 
    value: 64
  test_size:
    value: 256
  lr:
    value: 0.0001
    # values:
    #   - 0.00001
    #   - 0.0001
    #   - 0.001
  momentum:
    value: 0.99
    # values:
    #   - 0.9
    #   - 0.99
    #   - 0.999
  colour_space: 
    value: "RGB"
    # values:
    # - "RGB"
    # - "YCrCb"
  loss_function: 
    values: 
      # - "BCE"
      - "WBCE_9"
      # - "WBCE_5"
      # - "WBCE_10"
      # - "WBCE_20"
      # - "IoU"
      # - "Focal"
  optimizer:
    value: "Adam"
    # values: 
      # - "SGD"
      # - "RMSprop"
      # - "Adam"