program: WandBSkinSegmentation.py

# method: random
method: grid

project: "skin_segmentation"

metric:
  name: test_IoU
  goal: minimize

parameters:
  num_epochs:
    value: 5
  batch_size: 
    value: 64
  train_size: 
    value: 256
  test_size:
    value: 64
  lr:
    value: 0.01
    # distribution: uniform
    # min: 0.001
    # max: 0.01
  momentum:
    value: 0.9
    # distribution: uniform
    # min: 0.9
    # max: 0.99
  colour_space: 
    value: "RGB"
    # distribution: categorical
    # values:
    # - "RGB"
    # - "YCrCb"
  loss_function: 
    values: 
      # - "BCE"
      # - "WBCE"
      - "WBCE_0.9"
      # - "WBCE_0.1"
      - "IoU"
      # - "Focal"
  optimizer:
    values: 
      - "SGD"
      - "RMSprop"
      - "Adam"