wandb_version: 1

num_epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 32
train_size:
  desc: null
  value: 10000
test_size:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.999
colour_space:
  desc: null
  value: RGB
loss_function:
  desc: null
  value: L1
optimizer:
  desc: null
  value: Adam
device:
  desc: null
  value: cpu
dataset:
  desc: null
  value: Skin_NonSkin
architecture:
  desc: null
  value: SkinClassifier
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700144747.049988
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.13
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
