wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 32
NUM_EPOCHS:
  desc: null
  value: 25
LR:
  desc: null
  value: 0.01
MOMENTUM:
  desc: null
  value: 0.99
TRAIN_SIZE:
  desc: null
  value: 128
TEST_SIZE:
  desc: null
  value: 32
dataset:
  desc: null
  value: VisuAAL
architecture:
  desc: null
  value: UNet
device:
  desc: null
  value: mps
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698996261.839971
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
